### ISSUE TITLE
create a new odt document - save and reopen -> document empty 

### ISSUE THREAD

**Issue by mniehren** [CollaboraOnline/richdocumentscode#271] opened 2024-05-29 12:05 UTC
Hi,

i am using NC 27.1.9 with latest Collabora 24.4.201.

If you create a new dokument over the menu (test.odt), do some inputs and save the file, then the
file is still empty. 
If you open an existsing file for editing everything work's fine.

best regards
  Michae

**Comment by timur-g** [comment] 2024-06-05 12:51
If you are using Built-in CODE, and I assume you do as you reported here which specifically is for Built-in CODE, please close, this is a duplicate of @238.

**Closed** 2024-06-05 15:07 UTC
