### ISSUE TITLE
Nextcloud 26 compatibility

### ISSUE THREAD

**Issue by jakobroehrl** [CollaboraOnline/richdocumentscode#215] opened 2023-03-15 19:09 UTC

**Comment by jakobroehrl** [comment] 2023-03-22 12:59
It works, tested it. 
But it would nice, if it would shown as compatible with NC26.

**Comment by elpraga** [comment] 2023-03-24 19:43
It would, indeed. It is rather strange if a crucial app like this one appears as incompatible with the new version.

**Comment by Lawkss** [comment] 2023-03-25 19:32
Is this being worked on?

**Comment by tigernero79** [comment] 2023-03-26 09:38
I think this is the real Achilles heel of all nextcloud plugins, you don't think about making plugins compatible from the start that are at the core of using nextcloud itself, releasing a new release and seeing a service that was used until stopped at version one means there is no coordination between essential plugins and the nextcloud team. see for e2e sometimes see for android mobile app which as of today doesn't allow deletion of files from e2e folders things you should test first i think.

Greetings

**Comment by mikeblack999** [comment] 2023-03-26 13:31
> 

How did you install it? I can't do it over App menu or occ, both shows it's not compatible because I don't have Nextcloud version 25 or below (also have 26)

**Comment by mikeblack999** [comment] 2023-03-26 13:33
> It works, tested it. But it would nice, if it would shown as compatible with NC26.

How did you install it? I can't do it over app menu or occ, both refuses because I don't have Nextcloud version 25 or below (also have 26)

**Comment by merwan** [comment] 2023-03-26 13:46
The installation can be forced in command line using the `-f` flag:
```bash
php -d memory_limit=512M ./occ app:install -f -v richdocumentscode
```

**Comment by gitgt** [comment] 2023-03-28 14:45
I have NC 25.03 and it doesn't offer NC 26 as a release, only as beta. But it says that Collabora Office is compatible with it.

**Comment by n-greene** [comment] 2023-04-10 14:15
If it works with NC 26, could it be updated to pass with the current release? That would be awesome!

**Comment by wizdude** [comment] 2023-04-11 04:57
the release of this on the app store is from November 2022. there have been some fixes since this time which would be good to get. i can see that a commit was done to set compatibility for Nextcloud 26, but there are also some other fixes which are not yet in a current release build.

would it be possible to get a new release done and have this checked into the app store? i'm keen to start testing this with the Nextcloud 26 server I just built in my lab, but i'm trying to avoid having to build this myself as a custom package.

**Comment by gitgt** [comment] 2023-04-11 07:12
"Issues" are bug reporting and some inputs. Please refrain from pointless "could you update", or update yourself, this is OS. 
Do not avoid building for yourself, rather write here your experience and how you made it.

**Comment by n-greene** [comment] 2023-04-12 21:17
> "Issues" are bug reporting and some inputs. Please refrain from pointless "could you update", or update yourself, this is OS. Do not avoid building for yourself, rather write here your experience and how you made it.

The 'report a problem' and 'request feature' buttons at https://apps.nextcloud.com/apps/richdocumentscode point here. Validly so do bug reports and issues, as I you pointed out. I hardly think wanting the code server to be compatible with NC 26 is pointless, I hope you don't speak for all of Collabora @gitgt

**Comment by timar** [comment] 2023-04-14 20:11
The new release 22.5.1301 has the Nextcloud 26 compatibility commit in it, so I think this issue can be closed. Sorry for the delay, the versions between 22.5.802 and 22.5.1301 simply did not work due to a heisenbug! So we did not relase them.

**Closed by timar** 2023-04-14 20:11 UTC

**Comment by n-greene** [comment] 2023-04-14 20:29
Andras

Thanks very much for addressing this issue. I can confirm that the update
worked. However when I exit out of Collabora to my NC instance I get a
blank screen - background only. Should I file an issue on the Git page?

Nic Greene
