### ISSUE TITLE
can't disable welcome message

### ISSUE THREAD

**Issue by himpierre** [CollaboraOnline/richdocumentscode#183] opened 2022-05-05 15:59 UTC
hi devs!

I can't disable the welcome message. Whenever I open a document in nextcloud (23,24) i get the welcome message. I set the "welcome enable" to false in coolwsd.xml like this:

```
        <welcome>
                <enable default="false" desc="Controls whether the welcome screen should be shown to the users on new install and updates." type="bool">false</enable>
                <enable_button default="false" desc="Controls whether the welcome screen should have an explanatory button instead of an X button to close the dialog." type="bool">false</enable_button>
                <path default="browser/welcome" desc="Path to 'welcome-$lang.html' files served on first start or when the version changes. When empty, defaults to the Release notes." relative="true" type="path"/>
        </welcome>
```

I would expect that disables the welcome message all together. What do I miss?

cheers, t.

**Comment by manu-p** [comment] 2022-06-23 13:04
Hi, sorry this is not a solution, but I too was wondering how to avoid these "welcome popups" and found there's no <welcome> tag in a standard coolwsd.xml file as it was with loolwsd.xml.

Is it that this is no longer an option and everyone has to face these popups, most of the time in a language she/he does not understand?

And what about [this commit](https://github.com/CollaboraOnline/online/blob/master/coolwsd-welcome.xml) dated march 30?

I don't understand.

**Comment by gitgt** [comment] 2023-03-29 07:45
Seems not specific to Built-in and a duplicate of https://github.com/CollaboraOnline/online/issues/4489.

**Closed by gitgt** 2023-03-29 07:45 UTC
