### ISSUE TITLE
Blank page and "loolmount incorrect user-name, other than 'lool'"

### ISSUE THREAD

**Issue by gcommit** [CollaboraOnline/richdocumentscode#135] opened 2021-07-12 13:58 UTC
Installed:
Ubuntu 18.04
Nextcloud 21.0.3
PHP 7.4
Apache2 2.4.48
Collabora Online (richdocuments) 4.1.2
Collabora Online CODE 6.4.1003

When i start a Nextcloud, go to App Store and install the two Collabora apps, everything is fine. In the settings i see a "Connected"

![Bildschirmfoto 2021-07-12 um 15 56 55](https://user-images.githubusercontent.com/18714033/125299825-ca2c5780-e329-11eb-9ee5-6fa1b1b2e279.png)

But as soon as i want to open a document (or to reload my view of the document) the following output is generated:
```
web_1  | ==> /var/log/apache2/error.log <==
web_1  | [Mon Jul 12 13:52:51.973187 2021] [php7:notice] [pid 1147] [client 127.0.0.1:57640] richdocumentscode (proxy.php) error exit, PID: 1147, Message: Timed out opening local socket: 99 - Cannot assign requested address
web_1  | Security: loolforkit incorrect user-name, other than 'lool'
web_1  | Security: Check for the 'lool' username overridden on the command line.
web_1  | Init vcl
web_1  | preload: merged unordf ucpchelp1 msforms vbaobj pcr vbaswobj sw animcore hwp flash chartcore solver sc wpftcalc xof ucpcmis1 wpftdraw sd svgfilter evtatt graphicfilter wpftimpress sdfilt sm pdffilter PresentationMinimizer protocolhandler ucpdav1 wpftwriter msword writerfilter t602filter xmlfa basctl binaryurp uuresolver scd chartcontroller ldapbe2 dba sdbt deploymentgui migrationoo2 migrationoo3 xsltfilter sdd embobj emboleobj log expwrap odfflatxml textfd storagefd xmlfd frm fwl fwm io textconversiondlgs smd mozbootstrap oox scfilt slideshow proxyfac vclcanvas canvasfactory mtfrenderer simplecanvas dlgprov basprov stringresource dbaxml calc dbase flat writer reflection bootstrap introspection invocation invocadapt namingservice stocservices cached1 ucppkg1 srtrs1 ucptdoc1 xsltdlg swd cui bib guesslang numbertext offacc scn scriptframe dbpool2 xmlsecurity analysis date pricing fps_office i18nsearch xsec_xmlsec emfio vbaevents pdfimport mysql_jdbc ucpext hyphen spell lnth for ctl passwordcontainer svgio
web_1  | Absent (often optional): sm sm sm sm sm sm sm sm sm sm sm smd
web_1  | Disabled: ucpftp1 rptxml dbu rptui rpt mork odbc sdbc2 cmdmail syssh ucphier1 ucpimage PresenterScreen abp dbp updatefeed
web_1  | Whitelisted languages: de_DE el en_GB en_US es_ES fr_FR hu it nl pt_BR pt_PT ru
web_1  | Preloading dictionaries: de_DE en_US fr_FR it_IT nl_NL pt_BR [Mon Jul 12 13:52:54.588700 2021] [php7:warn] [pid 1145] [client 172.25.0.1:61196] PHP Warning:  file_get_contents(http://localhost:9983/hosting/capabilities): failed to open stream: HTTP request failed! in /var/www/nextcloud/apps/richdocumentscode/proxy.php on line 260
web_1  | ru_RU en_GB nl_BE pt_PT es_ES
web_1  | Preloading thesauri: de_DE en_US fr_FR it_IT nl_NL pt_BR ru_RU en_GB nl_BE pt_PT es_ES
web_1  | Preload icons
web_1  | Preload languages
web_1  | Preload fonts
web_1  | Ready to accept connections on port 9983.
web_1  |
web_1  |
web_1  | ==> /var/log/nextcloud.log <==
web_1  | {"reqId":"oU411yb5DWbdjVHA2kYL","level":2,"time":"2021-07-12T13:53:00+00:00","remoteAddr":"172.25.0.1","user":"admin","app":"no app in context","method":"GET","url":"/index.php/core/preview?fileId=101&c=60ec46878b41c&x=250&y=250&forceIcon=0&a=0","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15","version":"21.0.3.1"}
web_1  | {"reqId":"MSP4fR2bpi7Wh7qzVYG8","level":2,"time":"2021-07-12T13:53:00+00:00","remoteAddr":"172.25.0.1","user":"admin","app":"no app in context","method":"GET","url":"/index.php/core/preview?fileId=88&c=60ec466f7ba42&x=250&y=250&forceIcon=0&a=0","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15","version":"21.0.3.1"}
web_1  |
web_1  | ==> /var/log/apache2/error.log <==
web_1  | Security: loolmount incorrect user-name, other than 'lool'
web_1  | Aborting.
web_1  | Security: loolmount incorrect user-name, other than 'lool'
web_1  | Aborting.
web_1  | Security: loolmount incorrect user-name, other than 'lool'
web_1  | Aborting.
web_1  | [Mon Jul 12 13:53:33.365271 2021] [php7:notice] [pid 157] [client 172.25.0.1:61474] richdocumentscode (proxy.php) error exit, PID: 157, Message: No content in reply from loolwsd. Is SSL enabled in error ?
```

Followed by 

```
web_1  | ==> /var/log/apache2/error.log <==
web_1  | Security: loolmount incorrect user-name, other than 'lool'
web_1  | Aborting.
web_1  | Security: loolmount incorrect user-name, other than 'lool'
web_1  | Aborting.
web_1  | Security: loolmount incorrect user-name, other than 'lool'
web_1  | Aborting.
```

with every try to open a document. 
It is running inside of docker container and the ports 80 and 443 are open. 

What can i do?  :(

**Comment by bb** [comment] 2021-07-16 11:41
This issue still exists with 6.4.1004.

**Comment by gcommit** [comment] 2021-07-16 12:26
I started a new Nextcloud (22.0.0). Installed "Collabora Online - Built-in CODE Server" and "Collabora Online" in newest Versions 

Instant blank page

**Comment by jman0815** [comment] 2021-07-16 12:28
Same problem here!

**Comment by jhartmann44** [comment] 2021-07-16 12:32
I've been searching for a solution, bug remains.

**Comment by gcommit** [comment] 2021-07-19 09:55
Can anyone say something? At least "Hello" ?

**Comment by pwojcieszonek** [comment] 2021-07-19 18:48
Collabora 4.2.0 not working either.

**Comment by manu-p** [comment] 2021-07-22 09:30
Same here on:
Ubuntu 18.04.5
NC 20.0.9
Collabora Online - Built-in CODE Server 6.4.806 (too many bugs with 6.4.10!)
Collabora Online 3.8.3

**Comment by gcommit** [comment] 2021-07-28 13:47
any news here?

**Comment by gcommit** [comment] 2021-07-29 13:24
Can please someone answer? Not being able to open files is kind of critical in such a tool ...

**Comment by gcommit** [comment] 2021-08-04 15:10
HELLO?

**Comment by cornouws** [comment] 2021-08-04 20:51
Sorry, no insight on my side.
I assume that some that may have, are on holidays..

**Comment by gcommit** [comment] 2021-08-13 09:50
So we ... wait?

**Comment by dmanea28** [comment] 2021-08-16 11:44
Same for me. The editor opens, but I cannot save anything.

**Comment by EnderArchery** [comment] 2021-09-05 13:10
Same problem

**Comment by craiq** [comment] 2021-09-07 19:50
same problem!
Is there any hint to fix this?

**Comment by gcommit** [comment] 2021-09-08 14:22
unfortunately not .... sorry

**Comment by Michael-81** [comment] 2021-10-11 08:50
I have the same problem.

Is there a solution?

**Comment by ssmid** [comment] 2021-11-12 00:28
I edited proxy.php's launch cmd so that the AppImage is started with "--disable-lool-user-checking", but it gives me an error message "Option must not be given more than once: disable-lool-user-checking" and even segfaults from time to time. Pretty weird.

**Comment by ssmid** [comment] 2021-11-12 01:00
After several reboots, server restarts, cleanups, ever changing logs, error messages and behaviour, I'm giving up. I was able to get an instance running one single time but the next time it's gone once more without having changed anything. I won't try anymore. Nextcloud is great; PHP, Javascript and web dev in general are certainly not. And AppImages seem to be just another mess.

**Comment by pawanrai9999** [comment] 2021-11-12 02:43
Well this issue still exists in Nextcloud 22. I think we will need to run our own colabra online server. This is the only solution I can think of. I was able to work properly in one of my install earlier but I don't remember how I did it.

**Comment by mnn** [comment] 2022-04-02 14:10
I hit probably same issue. I am running nextcloud in the official docker container, installed both plugins from store and since I saw some missing libraries in logs, I installed them manually in the container (I think libfuse2 and libcap2). It didn't help.

```
[Sat Apr 02 15:58:45.516660 2022] [php:notice] [pid 35] [client 172.17.0.1:42922] richdocumentscode (proxy.php) error exit, PID: 35, Message: Timed out opening local socket: 99 - Cannot assign requested address
Security: coolforkit incorrect user-name, other than 'cool'
Security: --disable-cool-user-checking failed, coolforkit has some capabilities set.
Aborting.
```

**Comment by dg1sek** [comment] 2022-10-11 11:33
On Nextcloud Server 24.0.6 this still occurs.

**Comment by juliennicouleaud** [comment] 2022-10-28 08:06
It seems to work fine now! ->  Collabora Online - Built-in CODE Server 22.5.702 and Nextcloud Office 6.3.1.
(Nextcloud Server 24.0.6)

**Comment by Stef976** [comment] 2022-11-18 15:10
I had the same problem with Nextcloud 25.0.1. If this can help, I resolved the problem by allowing TSLv1.2 in apache.
I planned to only accept v1.3 but it seems that it's a problem for the app (curl errors in Logging).

**Comment by stephen304** [comment] 2022-11-23 21:56
I was having this issue with nextcloud docker 25.0.1, CODE 22.5.802, NC Office 7.0.1 when it was working before on the same versions. My error is slightly different in that it says `cool` instead of `lool`

```
Logging at warning level to file: /tmp/coolwsd.4hwBvUCWJL/coolwsd.log
172.16.176.4 -  23/Nov/2022:21:42:25 +0000 "GET /custom_apps/richdocumentscode/proxy.php" 200
172.16.176.4 -  23/Nov/2022:21:42:30 +0000 "GET /custom_apps/richdocumentscode/proxy.php" 200
172.16.176.4 -  23/Nov/2022:21:42:31 +0000 "GET /custom_apps/richdocumentscode/proxy.php" 200
NOTICE: PHP message: richdocumentscode (proxy.php) error exit, PID: 56, Message: Timed out opening local socket: 99 - Cannot assign requested address
172.16.176.4 -  23/Nov/2022:21:42:31 +0000 "GET /custom_apps/richdocumentscode/proxy.php" 400
172.16.176.4 -  23/Nov/2022:21:42:30 +0000 "GET /index.php" 200
172.16.176.4 -  23/Nov/2022:21:42:31 +0000 "GET /index.php" 200
172.16.176.4 -  23/Nov/2022:21:42:39 +0000 "GET /ocs/v2.php" 200
172.16.176.4 -  23/Nov/2022:21:42:40 +0000 "GET /index.php" 302
172.16.176.4 -  23/Nov/2022:21:42:40 +0000 "GET /index.php" 200
Security: coolforkit incorrect user-name, other than 'cool'
Init vcl
```

Oddly enough, I was able to fix this by navigating to `/settings/admin/richdocuments` and spam clicking the "Use built in code" radio button. When I had issues before, usually clicking this radio button once would often fix it, but this is the first time I needed to click it many times quickly to resolve the issue.

**Comment by martadinata666** [comment] 2023-03-11 09:14
Is this ever getting fixed? Version 22.5.802 + Nextcloud 25.0.4 , I mean real fix, not just some random `sudden` work thing.
```
nextcloud_web.1.y10dropjdghm@homelab    | Forced Exit with code: 70
nextcloud_web.1.y10dropjdghm@homelab    | Security: coolmount incorrect user-name, other than 'cool'
nextcloud_web.1.y10dropjdghm@homelab    | Aborting.
nextcloud_web.1.y10dropjdghm@homelab    | Security: coolmount incorrect user-name, other than 'cool'
nextcloud_web.1.y10dropjdghm@homelab    | Aborting.
nextcloud_web.1.y10dropjdghm@homelab    | Security: coolmount incorrect user-name, other than 'cool'
nextcloud_web.1.y10dropjdghm@homelab    | Aborting.
```

**Comment by SailReal** [comment] 2023-03-30 14:56
Also getting the `coolmount incorrect user-name, other than 'cool'` error on Nextcloud version 26.0.0 using the following deployment script: https://github.com/tomMoulard/make-my-server/blob/master/nextcloud/docker-compose.nextcloud.yml

But the strange this is on a different server using the same deployment file it works as expected :thinking:

**Comment by SysEngDan** [comment] 2023-04-29 16:56
This is really discouraging that this still isn't working.

**Comment by timar** [comment] 2023-05-02 09:01
`Security: coolmount incorrect user-name, other than 'cool' – Aborting.` is expexted, because it is a security check. In case of richdocumentscode the service is running by the user of the webserver (e.g. `www-data`) not by `cool`. I wonder why `coolmount` is invoked though, I would think it's a mistake, because we pass the `--o:mount_jail_tree="false"` in command line, when we start coolwsd. Having said that, I think it's still a red herring, because if bind mount fails, we fall back to link/copy, and it should work. It works for many people. So it's hard to tell what exactly should be fixed.

**Comment by negati0ns** [comment] 2023-09-16 11:22
Same for me.  I used the nextcloud-setup.php script on 3 different servers, all Ubuntu 22:04.  1 works perfectly, the other 2 lock up as soon as I enable CODE so I have to disable it and therefore can't edit any documents.

**Comment by mikelpr** [comment] 2024-08-27 19:27
august 2024 and the docker image still does this

**Comment by craiq** [comment] 2024-08-27 19:39
for me the solution was to activate FUSE on the machine where collabora runs

**Comment by EnderArchery** [comment] 2024-08-27 19:40
Yeah, you should honestly go for setting up another container with the
collabora image itself.... it's more pain than it should be, especially if
you have more than one trusted domain... but at least that works and...
once it does, it stays that way

Mikel Pérez ***@***.***> schrieb am Di., 27. Aug. 2024, 21:27:

**Comment by EnderArchery** [comment] 2024-08-27 19:42
That's weird, fuse was always available... in my case... but I am just
speaking from memory so no guarantees

Ender Archery ***@***.***> schrieb am Di., 27. Aug. 2024, 21:40:

**Comment by mikelpr** [comment] 2024-08-27 20:08
> Yeah, you should honestly go for setting up another container with the collabora image itself.... it's more pain than it should be, especially if you have more than one trusted domain... but at least that works and... once it does, it stays that way

sad, I wanted to test first if it's going to work for my usecase :(

**Comment by timur-g** [comment] 2024-08-28 05:58
Seems this ticket should be closed. It is in `richdocumentscode` meaning it is for Built-in CODE. Some confirmed they have no more problems. Just "does not work in all my servers" is not enough to keep open. 
Others that mention docker image should not comment here, rather in https://github.com/CollaboraOnline/online/issues with all details on setup and what was tried.

**Closed by timur-g** 2024-08-28 05:58 UTC

**Comment by EnderArchery** [comment] 2024-08-28 06:06
No, some people finding workarounds for a straight up unexplained behavior
doesn't mean it's fixed either.

Also... this is richdocumentscode repo... you know... the exact version
that everyone is having trouble with.
The workarounds usually mean running something else, other than built-in.
(It's not even working in the NextCloud docker image where the environment
is pretty well defined).

From how I read your response, there might be a misunderstanding. When
we're talking about the docker image not working, we mean the NextCloud
image for which we install the built-in version from the store.

If you close this ticket, you might as well deprecate richdocumentscode as
a whole... because it's not working.

Timur ***@***.***> schrieb am Mi., 28. Aug. 2024, 07:59:

**Comment by stephen304** [comment] 2024-08-28 12:55
For the record I am using built in code and this is one of the major issues that makes collabora unusable and a main reason I switched back to onlyoffice - I frequently and seemingly randomly needed to disable/enable the built-in-code app in order to get it to work again (I assume spam clicking the built in code radio button in the nextcloud settings also does something to restart something related to this). It also seemed to frequently get into a bugged state when updating nextcloud which led me to add a post-update script that disabled and re-enabled this app.

**Comment by timur-g** [comment] 2024-08-28 13:04
IIUC last two reporters use NC docker. 
That would be special case to general Built-in CODE in NC installation, which should not be an issue. 
So I would prefer to leave this one closed and you may open a new ticket.

**Comment by stephen304** [comment] 2024-08-28 13:13
I'm not sure I understand

> last two reporters use NC docker.

Does this mean you are not accepting bug reports from people using built-in-code with nc docker and only from users of built-in-code with NC installed on a bare os? It was my understanding that the official NC docker was the main supported install type.

> general Built-in CODE in NC installation, which should work fine

Does this mean that this issue is not present when NC is installed directly on the host os? If that is the case I was unaware that there was a difference and I will keep that in mind if I try to use this again.

**Comment by timur-g** [comment] 2024-08-28 13:19
This was reported for Built-in CODE without mentinoning docker. Built-in CODE in NC docker does not have to be the same issue.
It is not about not accepting reports, rather we should split old general issue with Built-in CODE from NC docker case. 
Even that works in general, so if that does not work for some users you should try to pinpoint why and open a separate report.

**Comment by EnderArchery** [comment] 2024-08-28 13:19
No... why? I use general installed NextCloud... if it's not working in the
controlled docker environment... it's also not working anywhere else. At
least my case seems to proof this.
It's a bug, almost no-one probably uses this built-in version anymore
because of it... please leave it open

Timur ***@***.***> schrieb am Mi., 28. Aug. 2024, 15:04:

**Comment by EnderArchery** [comment] 2024-08-28 13:23
This is the version from the app store right? If you follow the
installation instructions for NC with Apache to the letter, on a stock
ubuntu server. (As this is what I have tried to create on my end) it's not
working. If you install it from the app store in the nc docker environment,
it's not working. There doesn't appear to be a fix for it, other than
running a separate collabora container...
this is THE version that is broken, with no fix, such a long time later...
why would you close it?
Did you get it work?
Maybe try to do so?

Ender Archery ***@***.***> schrieb am Mi., 28. Aug. 2024, 15:19:

**Comment by EnderArchery** [comment] 2024-08-28 13:27
If we figure out the cause on one end, it most certainly has a high chance
of being the fix for the other as well.
And as evidenced by the nc docker users in this ticket: They have found it.
(Probably because this is the code base that causes the issue)

Ender Archery ***@***.***> schrieb am Mi., 28. Aug. 2024, 15:23:

**Comment by EnderArchery** [comment] 2024-08-28 13:29
Also, if this is an issue with the code itself. (Which is actually probable
because it stopped working with an update of this app)... this is still the
exact app that gets run inside of nc docker....
Why would... pls don't split it. If you split it, the next person will (at
least in my insignificant opinion) mark it as a duplicate and merge it
again.

Ender Archery ***@***.***> schrieb am Mi., 28. Aug. 2024, 15:27:
