### ISSUE TITLE
Could not establish connection to the Collabora Online server

### ISSUE THREAD

**Issue by wszhdg** [CollaboraOnline/richdocumentscode#89] opened 2020-10-30 05:14 UTC
I have aready installed Collabora Online and built-in. And in built-in setting I got this “You have the Collabora Online app enabled. For further information and configuration, please check: Settings > Administration > Collabora Online”. 

But when I use it on my collabora, I got this error” Could not establish connection to the Collabora Online server. This might be due to a missing configuration of your web server. For more information, please visit: Connecting Collabora Online Single Click with Nginx”.

However, I’m pretty sure that I have already change the setting on Nginx and it work fun. So, i can’t understand what’s happening. 

When I click built-in option on Collabora Online it will take a long time and give me the error as Could not establish connection to the Collabora Online server.  When I use chrome with f12 i got the error 500.

So, is there someone get the same error with me, and how to fix it.

One more things, when i try status code on richdocuments which show me lake fontconfig but i have already installed it on my server. And if I change the error code on proxy.php. The status code will change to starting. But whatever I do or the status Code give which back, I still get the error with ‘ Could not establish connection to the Collabora Online server’

**Comment by NthmAnTi** [comment] 2020-11-03 20:56
Same problem here, Ubuntu 18.04.4, Nextcloud 20.0.1, fontconfig and fuse are installed, `location ~ ^\/(?:index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider\/.+|.+\/richdocumentscode\/proxy)\.php(?:$|\/) {` is set.
```
/var/www/nextcloud/apps/richdocumentscode/collabora/Collabora_Online.AppImage
```
is started by Nextcloud and
```
loolwsd --config-file=/tmp/.mount_CollabG6BMy3/etc/loolwsd/loolwsd.xml --disable-lool-user-checking --port=9982 --lo-template-path=/tmp/.mount_CollabG6BMy3/opt/collaboraoffice6.4 --o:sys_template_path=/tmp/.mount_CollabG6BMy3/ --o:security.capabilities=false --o:security.seccomp=false --o:child_root_path=/tmp/loolwsd.DBH3Ui9SRc/jails --o:file_server_root_path=/tmp/.mount_CollabG6BMy3/usr/share/loolwsd --o:ssl.enable=false --o:net.proxy_prefix=true --o:storage.wopi.host[0]=.* --o:storage.wopi.host[0][@allow]=true --o:memproportion=50 --o:logging.file[@enable]=true --o:logging.file.property[0][@name]=path --o:logging.file.property[0]=/tmp/loolwsd.DBH3Ui9SRc/loolwsd.log --o:welcome.enable=false --o:mount_jail_tree=false
```
is listening on TCP port 9982.

`https://my.domain.com/apps/richdocumentscode/proxy.php?status` returns:
```json
{
"status":"OK"
}
```
and `http://localhost:9982/hosting/capabilities` on the NC-Server shows:
```json
{
"convert-to":{
    "available":true
},
"hasMobileSupport":true,
"hasProxyPrefix":true,
"hasTemplateSaveAs":false,
"hasTemplateSource":true,
"productName":"Collabora Online Development Edition",
"productVersion":"6.4.0",
"productVersionHash":"fec8240"
}
```

What else is needed for the connection to the app to work?

The only thing I noticed: when you start tha AppImage manualy with `sudo -u www-data /var/www/nextcloud/apps/richdocumentscode/collabora/Collabora_Online.AppImage` you get
```
Bootstrapping exception 'cannot open directory file:///root/collaboraoffice/4/user/registry/data'
```
This path does not exist anywhere in the filesystem.

**Comment by danielrheinbay** [comment] 2020-11-16 18:40
Is this a duplicate of #26?

**Comment by csolisr** [comment] 2021-01-31 18:29
I'm currently having the same issue with the ARM64 version specifically. Am I expected to modify the location string on Nginx to explicitly add `richdocumentscode_arm64` instead of just `richdocumentscode`?

**Comment by timar** [comment] 2021-03-21 18:51
> I'm currently having the same issue with the ARM64 version specifically. Am I expected to modify the location string on Nginx to explicitly add `richdocumentscode_arm64` instead of just `richdocumentscode`?

Yes, you need to use `richdocumentscode_arm64` in the location string.

**Comment by timar** [comment] 2021-03-21 18:52
Please reopen, if this issue persists with the latest release.

**Closed by timar** 2021-03-21 18:52 UTC
