### ISSUE TITLE
Error during installation on Synology DS218

### ISSUE THREAD

**Issue by StephanReich** [CollaboraOnline/richdocumentscode#101] opened 2020-12-27 13:29 UTC
Hi,
I got the following error message during install using the CLI: 
sudo -u xxxxx php73 -d memory_limit=512M /volume1/web/nextcloud/occ app:install richdocumentscode

Error message:
Error: App "Collabora Online - Built-in CODE Server" cannot be installed because the following dependencies are not fulfilled: The following architectures are supported: x86_64

Maybe the documented command "install richdocumentscode" is wrong for the ARM technology? How can I install the right richdocumentcode application for ARM. Is there another install command?

My Synology system is running on a  supported aarch64 (uname -a):
Linux Diskstation 4.4.180+ #41222 SMP Fri Dec 4 19:00:10 CST 2020 aarch64 GNU/Linux synology_rtd1296_ds218

Thanks,
Stephan

**Comment by timar** [comment] 2021-03-21 17:43
Fixed the the documentation by 634e0bf2ee02619165739743706d500a98b9cf2c

**Comment by timar** [comment] 2021-03-21 17:44
It's a duplicate of #99

**Closed by timar** 2021-03-21 17:43 UTC
