### ISSUE TITLE
Please add compatibility with Nextcloud V23

### ISSUE THREAD

**Issue by leonardohlee** [CollaboraOnline/richdocumentscode#155] opened 2021-12-01 19:09 UTC
Please add compatibility with Nextcloud V23.

**Comment by fatalerrors80** [comment] 2021-12-01 22:55
Same issue here, after upgrade to NC 23, office documents can no longer be opened using built-in server. Same behavior with external Colabora Server even if not certain of the setup, installed as a try to fix.

**Comment by caasi-dev** [comment] 2021-12-02 11:17
duplicate of #154

**Comment by MichaelTrip** [comment] 2021-12-03 12:35
I have tried the new version on nextcloud 23.0.0 but it still doesn't work. The document i tried to open (an empty one) keeps loading and loading. I can see the appimage started but that's it. Is there anyway i can pull out more logs to help you with debugging? @caasi-dev

**Comment by caasi-dev** [comment] 2021-12-03 12:38
> I have tried the new version on nextcloud 23.0.0 but it still doesn't work. The document i tried to open (an empty one) keeps loading and loading. I can see the appimage started but that's it. Is there anyway i can pull out more logs to help you with debugging? @caasi-dev

Hey @MichaelTrip I am not the application developer, and I am not familiar with the appimage version, sorry

**Comment by MichaelTrip** [comment] 2021-12-03 12:59
> > I have tried the new version on nextcloud 23.0.0 but it still doesn't work. The document i tried to open (an empty one) keeps loading and loading. I can see the appimage started but that's it. Is there anyway i can pull out more logs to help you with debugging? @caasi-dev
> 
> Hey @MichaelTrip I am not the application developer, and I am not familiar with the appimage version, sorry

Sorry bro. I will file a bug then. Thanks :)

**Comment by caasi-dev** [comment] 2021-12-03 13:00
> > > I have tried the new version on nextcloud 23.0.0 but it still doesn't work. The document i tried to open (an empty one) keeps loading and loading. I can see the appimage started but that's it. Is there anyway i can pull out more logs to help you with debugging? @caasi-dev
> > 
> > 
> > Hey @MichaelTrip I am not the application developer, and I am not familiar with the appimage version, sorry
> 
> Sorry bro. I will file a bug then. Thanks :)

No problem at all ;-)

**Comment by fatalerrors80** [comment] 2021-12-03 20:05
Not related to CODE server : https://github.com/nextcloud/richdocuments/issues/1895

I suggest you close that ticket.

**Comment by leonardohlee** [comment] 2021-12-04 01:33
V5 Released for NC23

**Closed** 2021-12-04 01:33 UTC
